name: SoccerTraj
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohappyeyeballs=2.4.4=py310h06a4308_0
  - aiohttp=3.11.10=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-timeout=5.0.1=py310h06a4308_0
  - attrs=24.3.0=py310h06a4308_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_1
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.8.90=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.8=3
  - debugpy=1.8.13=py310hf71b8c6_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.5.0=py310h5eee18b_0
  - fsspec=2024.12.0=py310h06a4308_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - krb5=1.21.3=h143b758_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.13.1.3=0
  - libcurand=10.3.9.90=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py310h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - multidict=6.1.0=py310h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py310h06a4308_0
  - numexpr=2.10.1=py310h3c60e43_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.5.0=h7b32b05_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py310h6a678d5_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py310hcea889d_0
  - pip=25.0=py310h06a4308_0
  - platformdirs=4.3.7=pyh29332c3_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - propcache=0.3.1=py310h5eee18b_0
  - psutil=5.9.0=py310h5eee18b_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyg=2.6.1=py310_torch_2.4.0_cu121
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.4.0=py3.10_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py310h5eee18b_0
  - pyzmq=26.4.0=py310h71f11fc_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_1
  - scipy=1.15.2=py310h23a989f_1
  - setuptools=75.8.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.13.3=py310h06a4308_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.4.0=py310_cu121
  - torchtriton=3.0.0=py310
  - torchvision=0.19.0=py310_cu121
  - tornado=6.4.2=py310ha75aee5_0
  - tqdm=4.67.1=py310h2f386ee_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.12.2=py310h06a4308_0
  - typing_extensions=4.12.2=py310h06a4308_0
  - urllib3=2.3.0=py310h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py310h5eee18b_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - axial-positional-embedding==0.3.12
      - backcall==0.2.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - chainer==7.8.1
      - colt5-attention==0.11.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - cython==3.1.0
      - defusedxml==0.7.1
      - docopt==0.6.2
      - einops==0.8.1
      - fastjsonschema==2.21.1
      - floodlight==0.5.0
      - fonttools==4.57.0
      - h5py==3.13.0
      - hyper-connections==0.1.15
      - ipython==8.12.3
      - ipywidgets==8.1.6
      - iso8601==2.1.0
      - joblib==1.4.2
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.14
      - kiwisolver==1.4.8
      - koreanize-matplotlib==0.1.1
      - lightning-utilities==0.14.3
      - linear-attention-transformer==0.19.1
      - linformer==0.2.3
      - llvmlite==0.44.0
      - local-attention==1.11.1
      - lxml==5.3.2
      - matplotlib==3.10.1
      - mistune==3.1.3
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - numba==0.61.2
      - numpy==2.2.4
      - nvidia-ml-py==12.575.51
      - nvitop==1.5.1
      - pandocfilters==1.5.1
      - pip-chill==1.0.3
      - pipreqs==0.5.0
      - product-key-memory==0.2.11
      - protobuf==6.30.2
      - pytz==2024.2
      - referencing==0.36.2
      - rpds-py==0.26.0
      - scikit-learn==1.6.1
      - seaborn==0.13.2
      - six==1.17.0
      - soupsieve==2.7
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - torch-scatter==2.1.2+pt24cu121
      - torchmetrics==1.7.1
      - tslearn==0.6.3
      - tzdata==2025.2
      - webencodings==0.5.1
      - widgetsnbextension==4.0.14
      - yarg==0.1.9
prefix: /home/park/anaconda3/envs/SoccerTraj
